### PR TITLE
Updating functions and vignettes

### PR DESCRIPTION
**Pull request by rvalavi**
- Just some small changes in the functions
- Documentations are updated
- The function disMapBook is updated by the base plots
- No dependency on other packages
- Add mapview to suggests

### CODE REVIEW

**Comment by rhijmans** [comment]
Great, checked clean. I removed the compiled vignettes as they are redundant and gave a warning with build.

**Comment by rvalavi** [comment]
Wonderful. Thanks. 
The reason I add them is that When I remove the complied vignettes, I couldn't see them on the help page.

**Comment by rhijmans** [comment]
Ah, your are right. I do not know now why that is, but I put them back in!

**Comment by rvalavi** [comment]
I have no idea; and the R package projects no longer generate the compiled html files.
Thanks

**Pull request merged**
